name: release and push to central
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java and Maven settings
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: central
          server-username: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          server-password: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
        
      - name: Import GPG key
        run: |
          mkdir -p ~/.gnupg
          printf "%s" "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" | gpg --batch --import
          
      - name: Debug GPG key length
        env:
          GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        run: |
          echo "Key length = ${#GPG_PRIVATE_KEY}"
          
      - name: Check GPG keys after import
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Deploy to Central Portal
        env:
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: mvn clean deploy -Dgpg.passphrase="$GPG_PASSPHRASE" --batch-mode