name: release and push to central
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java and Maven settings
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: central
          server-username: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          server-password: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
        
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          printf "%s" "$GPG_PRIVATE_KEY" | tr -d '\r' | gpg --batch --import
          # optionally trust the key or configure pinentry:
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf

      - name: Deploy to Central Portal
        env:
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: mvn clean deploy -Dgpg.passphrase="$MAVEN_GPG_PASSPHRASE" --batch-mode